### ISSUE TITLE
Como integrar os 3 tipos juntos

### ISSUE THREAD

**Issue by andrelacomski** [Rocketseat/blog-react-navigation#2]
Estou com uma dúvida, no exemplo é feito de forma separada o createStackNavigator, createDrawerNavigator.
Como eu posso colocar os dois juntos no meu app? ou não seria o ideal fazer isso

**Comment by diego3g** [comment]
Consegue sim, você pode ter pra cada página do Drawer um Stack, algo assim:
```js
createDrawerNavigator({
  Dashboard: createStackNavigator({
    Tela1,
    Tela2,
  })
})
```
